/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.wendel.pdv.view;

import br.com.wendel.pdv.controller.CidadesController;
import br.com.wendel.pdv.App;
import br.com.wendel.pdv.entity.Estado;
import br.com.wendel.pdv.util.Border;
import br.com.wendel.pdv.util.Consulta;
import br.com.wendel.pdv.util.Cores;
import static br.com.wendel.pdv.util.Mensagem.enviarMensagemErro;
import br.com.wendel.pdv.util.TraversalPolicy;
import java.awt.event.KeyEvent;
import static java.util.Arrays.asList;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author INLOC01
 */
public class CidadesView extends javax.swing.JPanel {

    private final CidadesController cidadesViewController;
    private final CidadeTableModel cidadeTableModel;
    private final JTableCustom<Map<String, Object>> tabela;

    /**
     * Creates new form HomeView
     *
     * @throws java.lang.Exception
     */
    public CidadesView() throws Exception {
        this.cidadesViewController = new CidadesController();
        this.cidadeTableModel = new CidadeTableModel();
        this.tabela = new JTableCustom<>(this.cidadeTableModel);
        initComponents();
        this.jCBEstado.addItem(null);
        for (Estado value : Estado.values()) {
            this.jCBEstado.addItem(value);
        }
    }

    public void carregaTela(String descricao, Estado estado) throws Exception {
        this.jTFDescricao.setText(descricao);
        this.jCBEstado.setSelectedItem(estado);
        this.jPButtonNovo.setBackground(Cores.COR_BOTAO_MENU);
        this.jPButtonEditar.setBackground(Cores.COR_BOTAO_MENU);
        this.jPButtonExcluir.setBackground(Cores.COR_BOTAO_MENU);
        this.acaoPesquisar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPTopo = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        jPButtonNovo = new javax.swing.JPanel();
        jLButtonNovo = new javax.swing.JLabel();
        jLIconButtonNovo = new javax.swing.JLabel();
        jPButtonExcluir = new javax.swing.JPanel();
        jLButtonExcluir = new javax.swing.JLabel();
        jLIconButtonExcluir = new javax.swing.JLabel();
        jPButtonEditar = new javax.swing.JPanel();
        jLButtonEditar = new javax.swing.JLabel();
        jLIconButtonEditar = new javax.swing.JLabel();
        jSPCaixas = new JScrollPane(this.tabela);
        jPButtonCancelar = new javax.swing.JPanel();
        jLButtonCancelar = new javax.swing.JLabel();
        jLIconButtonCancelar = new javax.swing.JLabel();
        jPButtonSalvar = new javax.swing.JPanel();
        jLButtonSalvar = new javax.swing.JLabel();
        jLIconButtonSalvar = new javax.swing.JLabel();
        jLDescricao = new javax.swing.JLabel();
        jTFDescricao = new javax.swing.JTextField();
        jPButtonPesquisar = new javax.swing.JPanel();
        jLButtonPesquisar = new javax.swing.JLabel();
        jLIconButtonPesquisar = new javax.swing.JLabel();
        jLDescricao1 = new javax.swing.JLabel();
        jCBEstado = new javax.swing.JComboBox<Estado>();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setFocusTraversalPolicy(new TraversalPolicy(asList(this.jTFDescricao, this.jCBEstado, this.jPButtonPesquisar, this.jPButtonSalvar, this.jPButtonCancelar, this.jPButtonNovo, this.jPButtonEditar, this.jPButtonExcluir)));
        setFocusTraversalPolicyProvider(true);

        jPTopo.setBackground(new java.awt.Color(79, 195, 247));
        jPTopo.setPreferredSize(new java.awt.Dimension(85, 35));

        jLTitulo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLTitulo.setText("Cidades");

        jPButtonNovo.setBackground(new java.awt.Color(79, 195, 247));
        jPButtonNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPButtonNovo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPButtonNovoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPButtonNovoFocusLost(evt);
            }
        });
        jPButtonNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPButtonNovoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPButtonNovoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPButtonNovoMouseExited(evt);
            }
        });
        jPButtonNovo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPButtonNovoKeyPressed(evt);
            }
        });

        jLButtonNovo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLButtonNovo.setForeground(new java.awt.Color(255, 255, 255));
        jLButtonNovo.setText("Nova");

        jLIconButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wendel/pdv/images/icon_add.png"))); // NOI18N

        javax.swing.GroupLayout jPButtonNovoLayout = new javax.swing.GroupLayout(jPButtonNovo);
        jPButtonNovo.setLayout(jPButtonNovoLayout);
        jPButtonNovoLayout.setHorizontalGroup(
            jPButtonNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPButtonNovoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLIconButtonNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLButtonNovo)
                .addGap(10, 10, 10))
        );
        jPButtonNovoLayout.setVerticalGroup(
            jPButtonNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLIconButtonNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLButtonNovo, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPButtonExcluir.setBackground(new java.awt.Color(79, 195, 247));
        jPButtonExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPButtonExcluir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPButtonExcluirFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPButtonExcluirFocusLost(evt);
            }
        });
        jPButtonExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPButtonExcluirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPButtonExcluirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPButtonExcluirMouseExited(evt);
            }
        });
        jPButtonExcluir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPButtonExcluirKeyPressed(evt);
            }
        });

        jLButtonExcluir.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLButtonExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jLButtonExcluir.setText("Excluir");

        jLIconButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wendel/pdv/images/icon_delete.png"))); // NOI18N

        javax.swing.GroupLayout jPButtonExcluirLayout = new javax.swing.GroupLayout(jPButtonExcluir);
        jPButtonExcluir.setLayout(jPButtonExcluirLayout);
        jPButtonExcluirLayout.setHorizontalGroup(
            jPButtonExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPButtonExcluirLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLIconButtonExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLButtonExcluir)
                .addGap(10, 10, 10))
        );
        jPButtonExcluirLayout.setVerticalGroup(
            jPButtonExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLIconButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPButtonEditar.setBackground(new java.awt.Color(79, 195, 247));
        jPButtonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPButtonEditar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPButtonEditarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPButtonEditarFocusLost(evt);
            }
        });
        jPButtonEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPButtonEditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPButtonEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPButtonEditarMouseExited(evt);
            }
        });
        jPButtonEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPButtonEditarKeyPressed(evt);
            }
        });

        jLButtonEditar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLButtonEditar.setForeground(new java.awt.Color(255, 255, 255));
        jLButtonEditar.setText("Editar");

        jLIconButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wendel/pdv/images/icon_edit.png"))); // NOI18N

        javax.swing.GroupLayout jPButtonEditarLayout = new javax.swing.GroupLayout(jPButtonEditar);
        jPButtonEditar.setLayout(jPButtonEditarLayout);
        jPButtonEditarLayout.setHorizontalGroup(
            jPButtonEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPButtonEditarLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLIconButtonEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLButtonEditar)
                .addGap(10, 10, 10))
        );
        jPButtonEditarLayout.setVerticalGroup(
            jPButtonEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLIconButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPTopoLayout = new javax.swing.GroupLayout(jPTopo);
        jPTopo.setLayout(jPTopoLayout);
        jPTopoLayout.setHorizontalGroup(
            jPTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTopoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 479, Short.MAX_VALUE)
                .addComponent(jPButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPTopoLayout.setVerticalGroup(
            jPTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPButtonNovo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jSPCaixas.setBackground(new java.awt.Color(255, 255, 255));
        jSPCaixas.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jSPCaixas.setForeground(new java.awt.Color(255, 255, 255));

        jPButtonCancelar.setBackground(new java.awt.Color(220, 53, 69));
        jPButtonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPButtonCancelar.setPreferredSize(new java.awt.Dimension(106, 35));
        jPButtonCancelar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPButtonCancelarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPButtonCancelarFocusLost(evt);
            }
        });
        jPButtonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPButtonCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPButtonCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPButtonCancelarMouseExited(evt);
            }
        });
        jPButtonCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPButtonCancelarKeyPressed(evt);
            }
        });

        jLButtonCancelar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jLButtonCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLButtonCancelar.setText("Cancelar");

        jLIconButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wendel/pdv/images/icon_cancel.png"))); // NOI18N

        javax.swing.GroupLayout jPButtonCancelarLayout = new javax.swing.GroupLayout(jPButtonCancelar);
        jPButtonCancelar.setLayout(jPButtonCancelarLayout);
        jPButtonCancelarLayout.setHorizontalGroup(
            jPButtonCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPButtonCancelarLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLIconButtonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPButtonCancelarLayout.setVerticalGroup(
            jPButtonCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(jLIconButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPButtonSalvar.setBackground(new java.awt.Color(0, 123, 255));
        jPButtonSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPButtonSalvar.setPreferredSize(new java.awt.Dimension(106, 35));
        jPButtonSalvar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPButtonSalvarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPButtonSalvarFocusLost(evt);
            }
        });
        jPButtonSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPButtonSalvarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPButtonSalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPButtonSalvarMouseExited(evt);
            }
        });
        jPButtonSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPButtonSalvarKeyPressed(evt);
            }
        });

        jLButtonSalvar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLButtonSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jLButtonSalvar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLButtonSalvar.setText("Selecionar");

        jLIconButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wendel/pdv/images/icon_save.png"))); // NOI18N

        javax.swing.GroupLayout jPButtonSalvarLayout = new javax.swing.GroupLayout(jPButtonSalvar);
        jPButtonSalvar.setLayout(jPButtonSalvarLayout);
        jPButtonSalvarLayout.setHorizontalGroup(
            jPButtonSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPButtonSalvarLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLIconButtonSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPButtonSalvarLayout.setVerticalGroup(
            jPButtonSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(jLIconButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLDescricao.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLDescricao.setText("Descrição");

        jTFDescricao.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTFDescricao.setToolTipText("Sigla da unidade");
        jTFDescricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFDescricaoFocusGained(evt);
            }
        });
        jTFDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFDescricaoKeyPressed(evt);
            }
        });

        jPButtonPesquisar.setBackground(new java.awt.Color(0, 123, 255));
        jPButtonPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPButtonPesquisar.setPreferredSize(new java.awt.Dimension(106, 35));
        jPButtonPesquisar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPButtonPesquisarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPButtonPesquisarFocusLost(evt);
            }
        });
        jPButtonPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPButtonPesquisarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPButtonPesquisarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPButtonPesquisarMouseExited(evt);
            }
        });
        jPButtonPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPButtonPesquisarKeyPressed(evt);
            }
        });

        jLButtonPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLButtonPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        jLButtonPesquisar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLButtonPesquisar.setText("Pesquisar");

        jLIconButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wendel/pdv/images/icon_save.png"))); // NOI18N

        javax.swing.GroupLayout jPButtonPesquisarLayout = new javax.swing.GroupLayout(jPButtonPesquisar);
        jPButtonPesquisar.setLayout(jPButtonPesquisarLayout);
        jPButtonPesquisarLayout.setHorizontalGroup(
            jPButtonPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPButtonPesquisarLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLIconButtonPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLButtonPesquisar)
                .addGap(10, 10, 10))
        );
        jPButtonPesquisarLayout.setVerticalGroup(
            jPButtonPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLButtonPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(jLIconButtonPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLDescricao1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLDescricao1.setText("UF");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTopo, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSPCaixas)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFDescricao)
                            .addComponent(jLDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLDescricao1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jPButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPTopo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLDescricao)
                            .addComponent(jLDescricao1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFDescricao)
                            .addComponent(jCBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSPCaixas, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jSPCaixas.getViewport().setBackground(new java.awt.Color(255, 255, 255));
    }// </editor-fold>//GEN-END:initComponents

    private void jPButtonNovoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonNovoMouseEntered
        SwingUtilities.invokeLater(() -> {
            this.jPButtonNovo.setBackground(Cores.COR_BOTAO_MENU_ENTERED);
        });
    }//GEN-LAST:event_jPButtonNovoMouseEntered

    private void jPButtonNovoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonNovoMouseExited
        SwingUtilities.invokeLater(() -> {
            this.jPButtonNovo.setBackground(Cores.COR_BOTAO_MENU);
        });
    }//GEN-LAST:event_jPButtonNovoMouseExited

    private void jPButtonExcluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonExcluirMouseEntered
        SwingUtilities.invokeLater(() -> {
            this.jPButtonExcluir.setBackground(Cores.COR_BOTAO_MENU_ENTERED);
        });
    }//GEN-LAST:event_jPButtonExcluirMouseEntered

    private void jPButtonExcluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonExcluirMouseExited
        SwingUtilities.invokeLater(() -> {
            this.jPButtonExcluir.setBackground(Cores.COR_BOTAO_MENU);
        });
    }//GEN-LAST:event_jPButtonExcluirMouseExited

    private void jPButtonEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonEditarMouseEntered
        SwingUtilities.invokeLater(() -> {
            this.jPButtonEditar.setBackground(Cores.COR_BOTAO_MENU_ENTERED);
        });
    }//GEN-LAST:event_jPButtonEditarMouseEntered

    private void jPButtonEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonEditarMouseExited
        SwingUtilities.invokeLater(() -> {
            this.jPButtonEditar.setBackground(Cores.COR_BOTAO_MENU);
        });
    }//GEN-LAST:event_jPButtonEditarMouseExited

    private void jPButtonNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonNovoMouseClicked
        try {
            this.acaoNovo();
        } catch (Exception e) {
            enviarMensagemErro(e.getMessage());
        }
    }//GEN-LAST:event_jPButtonNovoMouseClicked

    private void jPButtonEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonEditarMouseClicked
        try {
            this.acaoEditar();
        } catch (Exception e) {
            enviarMensagemErro(e.getMessage());
        }
    }//GEN-LAST:event_jPButtonEditarMouseClicked

    private void acaoEditar() throws Exception {
        Map<String, Object> cidadeSelecionada = this.tabela.getSelected();
        if (cidadeSelecionada != null) {
            App.getInstance().getPrincipalView().mostraConteudo(new CidadeCadastroView((Long) cidadeSelecionada.get("ID")));
        }
    }

    private void jPButtonExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonExcluirMouseClicked
        try {
            this.acaoExcluir();
        } catch (Exception e) {
            enviarMensagemErro(e.getMessage());
        }
    }//GEN-LAST:event_jPButtonExcluirMouseClicked

    private void acaoExcluir() throws Exception {
        Map<String, Object> cidadeSelecionado = this.tabela.getSelected();
        if (cidadeSelecionado != null
                && ConfirmDialog.confirm(App.getInstance().getPrincipalView(), "Exclusão",
                        "<html>Deseja excluir a cidade selecionada?")) {
            this.cidadesViewController.delete((Long) cidadeSelecionado.get("ID"));
            this.acaoPesquisar();
        }
    }

    private void jPButtonCancelarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPButtonCancelarFocusGained
        SwingUtilities.invokeLater(() -> {
            this.jPButtonCancelar.setBorder(BorderFactory.createDashedBorder(null, 1, 5, 5, false));
        });
    }//GEN-LAST:event_jPButtonCancelarFocusGained

    private void jPButtonCancelarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPButtonCancelarFocusLost
        SwingUtilities.invokeLater(() -> {
            this.jPButtonCancelar.setBorder(null);
        });
    }//GEN-LAST:event_jPButtonCancelarFocusLost

    private void jPButtonCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonCancelarMouseClicked
        try {
            this.acaoCancelar();
        } catch (Exception e) {
            enviarMensagemErro(e.getMessage());
        }
    }//GEN-LAST:event_jPButtonCancelarMouseClicked

    private void acaoCancelar() {
        Consulta consulta = Consulta.getInstance();
        if (consulta.isConsulta()) {
            JPanel janela = (JPanel) consulta.getJanelaRetorno();
            consulta.removerJanela();
            App.getInstance().getPrincipalView().mostraConteudo(janela);
        } else {
            App.getInstance().getPrincipalView().mostraTelaHome();
        }
    }

    private void acaoSelecionar() {
        try {
            Consulta consulta = Consulta.getInstance();
            if (consulta.isConsulta()) {
                Map<String, Object> item = this.tabela.getSelected();
                if (item != null) {
                    JPanel janela = (JPanel) consulta.getJanelaRetorno();
                    App.getInstance().getPrincipalView().mostraConteudo(janela);
                    ConsultaView consultaView = (ConsultaView) consulta.getJanelaRetorno();
                    consultaView.acaoSelecionarConsulta("idCidade", item.get("ID"));
                    consulta.removerJanela();
                }
            }
        } catch (Exception e) {
            enviarMensagemErro(e.getMessage());
        }
    }


    private void jPButtonCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonCancelarMouseEntered
        SwingUtilities.invokeLater(() -> {
            this.jPButtonCancelar.setBackground(Cores.COR_BOTAO_CANCELAR_ENTERED);
        });
    }//GEN-LAST:event_jPButtonCancelarMouseEntered

    private void jPButtonCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonCancelarMouseExited
        SwingUtilities.invokeLater(() -> {
            this.jPButtonCancelar.setBackground(Cores.COR_BOTAO_CANCELAR);
        });
    }//GEN-LAST:event_jPButtonCancelarMouseExited

    private void jPButtonCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPButtonCancelarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_SPACE) {
            this.acaoCancelar();
        }
    }//GEN-LAST:event_jPButtonCancelarKeyPressed

    private void jPButtonSalvarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPButtonSalvarFocusGained
        SwingUtilities.invokeLater(() -> {
            this.jPButtonSalvar.setBorder(BorderFactory.createDashedBorder(null, 1, 5, 5, false));
        });
    }//GEN-LAST:event_jPButtonSalvarFocusGained

    private void jPButtonSalvarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPButtonSalvarFocusLost
        SwingUtilities.invokeLater(() -> {
            this.jPButtonSalvar.setBorder(null);
        });
    }//GEN-LAST:event_jPButtonSalvarFocusLost

    private void jPButtonSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonSalvarMouseClicked
        this.acaoSelecionar();
    }//GEN-LAST:event_jPButtonSalvarMouseClicked

    private void jPButtonSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonSalvarMouseEntered
        SwingUtilities.invokeLater(() -> {
            this.jPButtonSalvar.setBackground(Cores.COR_BOTAO_SALVAR_ENTERED);
        });
    }//GEN-LAST:event_jPButtonSalvarMouseEntered

    private void jPButtonSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonSalvarMouseExited
        SwingUtilities.invokeLater(() -> {
            this.jPButtonSalvar.setBackground(Cores.COR_BOTAO_SALVAR);
        });
    }//GEN-LAST:event_jPButtonSalvarMouseExited

    private void jPButtonSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPButtonSalvarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_SPACE) {
            this.acaoSelecionar();
        }
    }//GEN-LAST:event_jPButtonSalvarKeyPressed

    private void jTFDescricaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFDescricaoFocusGained
        SwingUtilities.invokeLater(() -> {
            this.jTFDescricao.selectAll();
        });
    }//GEN-LAST:event_jTFDescricaoFocusGained

    private void jTFDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDescricaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            SwingUtilities.invokeLater(() -> {
                this.jPButtonPesquisar.requestFocusInWindow();
            });
        }
    }//GEN-LAST:event_jTFDescricaoKeyPressed

    private void jPButtonPesquisarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPButtonPesquisarFocusGained
        SwingUtilities.invokeLater(() -> {
            this.jPButtonPesquisar.setBorder(Border.BORDER_FOCUS_GAINED);
        });
    }//GEN-LAST:event_jPButtonPesquisarFocusGained

    private void jPButtonPesquisarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPButtonPesquisarFocusLost
        SwingUtilities.invokeLater(() -> {
            this.jPButtonPesquisar.setBorder(null);
        });
    }//GEN-LAST:event_jPButtonPesquisarFocusLost

    private void jPButtonPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonPesquisarMouseClicked
        try {
            this.acaoPesquisar();
        } catch (Exception e) {
            enviarMensagemErro(e.getMessage());
        }
    }//GEN-LAST:event_jPButtonPesquisarMouseClicked

    private void jPButtonPesquisarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonPesquisarMouseEntered
        SwingUtilities.invokeLater(() -> {
            this.jPButtonPesquisar.setBackground(Cores.COR_BOTAO_SALVAR_ENTERED);
        });
    }//GEN-LAST:event_jPButtonPesquisarMouseEntered

    private void jPButtonPesquisarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonPesquisarMouseExited
        SwingUtilities.invokeLater(() -> {
            this.jPButtonPesquisar.setBackground(Cores.COR_BOTAO_SALVAR);
        });
    }//GEN-LAST:event_jPButtonPesquisarMouseExited

    private void jPButtonPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPButtonPesquisarKeyPressed
        try {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_SPACE) {
                this.acaoPesquisar();
            }
        } catch (Exception e) {
            enviarMensagemErro(e.getMessage());
        }
    }//GEN-LAST:event_jPButtonPesquisarKeyPressed

    private void jPButtonNovoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPButtonNovoFocusGained
        SwingUtilities.invokeLater(() -> {
            this.jPButtonNovo.setBorder(Border.BORDER_FOCUS_GAINED);
        });
    }//GEN-LAST:event_jPButtonNovoFocusGained

    private void jPButtonNovoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPButtonNovoFocusLost
        SwingUtilities.invokeLater(() -> {
            this.jPButtonNovo.setBorder(null);
        });
    }//GEN-LAST:event_jPButtonNovoFocusLost

    private void jPButtonEditarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPButtonEditarFocusGained
        SwingUtilities.invokeLater(() -> {
            this.jPButtonEditar.setBorder(Border.BORDER_FOCUS_GAINED);
        });
    }//GEN-LAST:event_jPButtonEditarFocusGained

    private void jPButtonEditarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPButtonEditarFocusLost
        SwingUtilities.invokeLater(() -> {
            this.jPButtonEditar.setBorder(null);
        });
    }//GEN-LAST:event_jPButtonEditarFocusLost

    private void jPButtonExcluirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPButtonExcluirFocusGained
        SwingUtilities.invokeLater(() -> {
            this.jPButtonExcluir.setBorder(Border.BORDER_FOCUS_GAINED);
        });
    }//GEN-LAST:event_jPButtonExcluirFocusGained

    private void jPButtonExcluirFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPButtonExcluirFocusLost
        SwingUtilities.invokeLater(() -> {
            this.jPButtonExcluir.setBorder(null);
        });
    }//GEN-LAST:event_jPButtonExcluirFocusLost

    private void jPButtonNovoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPButtonNovoKeyPressed
        try {
            if (asList(KeyEvent.VK_ENTER, KeyEvent.VK_SPACE).contains(evt.getKeyCode())) {
                this.acaoNovo();
            }
        } catch (Exception e) {
            enviarMensagemErro(e.getMessage());
        }
    }//GEN-LAST:event_jPButtonNovoKeyPressed

    private void jPButtonEditarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPButtonEditarKeyPressed
        try {
            if (asList(KeyEvent.VK_ENTER, KeyEvent.VK_SPACE).contains(evt.getKeyCode())) {
                this.acaoEditar();
            }
        } catch (Exception e) {
            enviarMensagemErro(e.getMessage());
        }
    }//GEN-LAST:event_jPButtonEditarKeyPressed

    private void jPButtonExcluirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPButtonExcluirKeyPressed
        try {
            if (asList(KeyEvent.VK_ENTER, KeyEvent.VK_SPACE).contains(evt.getKeyCode())) {
                this.acaoExcluir();
            }
        } catch (Exception e) {
            enviarMensagemErro(e.getMessage());
        }
    }//GEN-LAST:event_jPButtonExcluirKeyPressed

    private void acaoNovo() throws Exception {
        App.getInstance().getPrincipalView().mostraConteudo(new CidadeCadastroView(null));
    }

    private void acaoPesquisar() throws Exception {
        this.cidadesViewController.atualizaLista(this.jTFDescricao.getText(), this.jCBEstado.getSelectedItem() != null ? (Estado) this.jCBEstado.getSelectedItem() : null);
        this.cidadeTableModel.setLista(this.cidadesViewController.getList());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Estado> jCBEstado;
    private javax.swing.JLabel jLButtonCancelar;
    private javax.swing.JLabel jLButtonEditar;
    private javax.swing.JLabel jLButtonExcluir;
    private javax.swing.JLabel jLButtonNovo;
    private javax.swing.JLabel jLButtonPesquisar;
    private javax.swing.JLabel jLButtonSalvar;
    private javax.swing.JLabel jLDescricao;
    private javax.swing.JLabel jLDescricao1;
    private javax.swing.JLabel jLIconButtonCancelar;
    private javax.swing.JLabel jLIconButtonEditar;
    private javax.swing.JLabel jLIconButtonExcluir;
    private javax.swing.JLabel jLIconButtonNovo;
    private javax.swing.JLabel jLIconButtonPesquisar;
    private javax.swing.JLabel jLIconButtonSalvar;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JPanel jPButtonCancelar;
    private javax.swing.JPanel jPButtonEditar;
    private javax.swing.JPanel jPButtonExcluir;
    private javax.swing.JPanel jPButtonNovo;
    private javax.swing.JPanel jPButtonPesquisar;
    private javax.swing.JPanel jPButtonSalvar;
    private javax.swing.JPanel jPTopo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jSPCaixas;
    private javax.swing.JTextField jTFDescricao;
    // End of variables declaration//GEN-END:variables
}
