/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.wendel.pdv.view;

import br.com.wendel.pdv.util.Cores;
import static br.com.wendel.pdv.util.Mensagem.enviarMensagemErro;
import br.com.wendel.pdv.util.TraversalPolicy;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import static java.util.Arrays.asList;
import javax.swing.BorderFactory;
import javax.swing.SwingUtilities;

/**
 *
 * @author INLOC01
 */
public class ConfirmDialog extends javax.swing.JDialog {

    private boolean confirm = false;

    /**
     * Creates new form Confirmacao
     *
     * @param parent
     * @param title
     * @param message
     */
    public ConfirmDialog(java.awt.Frame parent, String title, String message) {
        super(parent, true);
        initComponents();
        this.jLTitle.setText(title);
        this.jLMessage.setText(message);
        this.setLocationRelativeTo(null);
        this.pack();
        this.jPButtonSim.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPButtonSim = new javax.swing.JPanel();
        jLButtonSim = new javax.swing.JLabel();
        jLIconButtonSim = new javax.swing.JLabel();
        jPButtonNao = new javax.swing.JPanel();
        jLButtonNao = new javax.swing.JLabel();
        jLIconButtonNao = new javax.swing.JLabel();
        jSeparator = new javax.swing.JSeparator();
        jPTopo = new javax.swing.JPanel();
        jLTitle = new javax.swing.JLabel();
        jLMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setFocusTraversalPolicy(new TraversalPolicy(asList(this.jPButtonSim, this.jPButtonNao)));
        setFocusTraversalPolicyProvider(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPButtonSim.setBackground(new java.awt.Color(0, 123, 255));
        jPButtonSim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPButtonSim.setPreferredSize(new java.awt.Dimension(74, 35));
        jPButtonSim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPButtonSimFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPButtonSimFocusLost(evt);
            }
        });
        jPButtonSim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPButtonSimMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPButtonSimMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPButtonSimMouseExited(evt);
            }
        });
        jPButtonSim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPButtonSimKeyPressed(evt);
            }
        });

        jLButtonSim.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLButtonSim.setForeground(new java.awt.Color(255, 255, 255));
        jLButtonSim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLButtonSim.setText("Sim");

        jLIconButtonSim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wendel/pdv/images/icon_save.png"))); // NOI18N

        javax.swing.GroupLayout jPButtonSimLayout = new javax.swing.GroupLayout(jPButtonSim);
        jPButtonSim.setLayout(jPButtonSimLayout);
        jPButtonSimLayout.setHorizontalGroup(
            jPButtonSimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPButtonSimLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLIconButtonSim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLButtonSim)
                .addGap(45, 45, 45))
        );
        jPButtonSimLayout.setVerticalGroup(
            jPButtonSimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLButtonSim, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(jLIconButtonSim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPButtonNao.setBackground(new java.awt.Color(220, 53, 69));
        jPButtonNao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPButtonNao.setPreferredSize(new java.awt.Dimension(106, 35));
        jPButtonNao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPButtonNaoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPButtonNaoFocusLost(evt);
            }
        });
        jPButtonNao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPButtonNaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPButtonNaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPButtonNaoMouseExited(evt);
            }
        });
        jPButtonNao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPButtonNaoKeyPressed(evt);
            }
        });

        jLButtonNao.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLButtonNao.setForeground(new java.awt.Color(255, 255, 255));
        jLButtonNao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLButtonNao.setText("Não");

        jLIconButtonNao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wendel/pdv/images/icon_save.png"))); // NOI18N

        javax.swing.GroupLayout jPButtonNaoLayout = new javax.swing.GroupLayout(jPButtonNao);
        jPButtonNao.setLayout(jPButtonNaoLayout);
        jPButtonNaoLayout.setHorizontalGroup(
            jPButtonNaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPButtonNaoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLIconButtonNao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLButtonNao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPButtonNaoLayout.setVerticalGroup(
            jPButtonNaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLButtonNao, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(jLIconButtonNao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPTopo.setBackground(new java.awt.Color(79, 195, 247));
        jPTopo.setPreferredSize(new java.awt.Dimension(85, 35));

        jLTitle.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLTitle.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPTopoLayout = new javax.swing.GroupLayout(jPTopo);
        jPTopo.setLayout(jPTopoLayout);
        jPTopoLayout.setHorizontalGroup(
            jPTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTopoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPTopoLayout.setVerticalGroup(
            jPTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jLMessage.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLMessage.setPreferredSize(new java.awt.Dimension(0, 21));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator)
            .addComponent(jPTopo, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 194, Short.MAX_VALUE)
                        .addComponent(jPButtonSim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPButtonNao, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPTopo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPButtonNao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPButtonSim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPButtonSimFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPButtonSimFocusGained
        SwingUtilities.invokeLater(() -> {
            this.jPButtonSim.setBorder(BorderFactory.createDashedBorder(null, 1, 5, 5, false));
        });
    }//GEN-LAST:event_jPButtonSimFocusGained

    private void jPButtonSimFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPButtonSimFocusLost
        SwingUtilities.invokeLater(() -> {
            this.jPButtonSim.setBorder(null);
        });
    }//GEN-LAST:event_jPButtonSimFocusLost

    private void jPButtonSimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonSimMouseClicked
        try {
            this.confirm = true;
            this.dispose();
        } catch (Exception e) {
            enviarMensagemErro(e.getMessage());
        }
    }//GEN-LAST:event_jPButtonSimMouseClicked

    private void jPButtonSimMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonSimMouseEntered
        SwingUtilities.invokeLater(() -> {
            this.jPButtonSim.setBackground(Cores.COR_BOTAO_SALVAR_ENTERED);
        });
    }//GEN-LAST:event_jPButtonSimMouseEntered

    private void jPButtonSimMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonSimMouseExited
        SwingUtilities.invokeLater(() -> {
            this.jPButtonSim.setBackground(Cores.COR_BOTAO_SALVAR);
        });
    }//GEN-LAST:event_jPButtonSimMouseExited

    private void jPButtonSimKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPButtonSimKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_SPACE) {
            this.jPButtonSimMouseClicked(null);
        }
    }//GEN-LAST:event_jPButtonSimKeyPressed

    private void jPButtonNaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPButtonNaoFocusGained
        SwingUtilities.invokeLater(() -> {
            this.jPButtonNao.setBorder(BorderFactory.createDashedBorder(null, 1, 5, 5, false));
        });
    }//GEN-LAST:event_jPButtonNaoFocusGained

    private void jPButtonNaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPButtonNaoFocusLost
        SwingUtilities.invokeLater(() -> {
            this.jPButtonNao.setBorder(null);
        });
    }//GEN-LAST:event_jPButtonNaoFocusLost

    private void jPButtonNaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonNaoMouseClicked
        try {
            this.confirm = false;
            this.dispose();
        } catch (Exception e) {
            enviarMensagemErro(e.getMessage());
        }
    }//GEN-LAST:event_jPButtonNaoMouseClicked

    private void jPButtonNaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonNaoMouseEntered
        SwingUtilities.invokeLater(() -> {
            this.jPButtonNao.setBackground(Cores.COR_BOTAO_CANCELAR_ENTERED);
        });
    }//GEN-LAST:event_jPButtonNaoMouseEntered

    private void jPButtonNaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonNaoMouseExited
        SwingUtilities.invokeLater(() -> {
            this.jPButtonNao.setBackground(Cores.COR_BOTAO_CANCELAR);
        });
    }//GEN-LAST:event_jPButtonNaoMouseExited

    private void jPButtonNaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPButtonNaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_SPACE) {
            this.jPButtonNaoMouseClicked(null);
        }
    }//GEN-LAST:event_jPButtonNaoKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLButtonNao;
    private javax.swing.JLabel jLButtonSim;
    private javax.swing.JLabel jLIconButtonNao;
    private javax.swing.JLabel jLIconButtonSim;
    private javax.swing.JLabel jLMessage;
    private javax.swing.JLabel jLTitle;
    private javax.swing.JPanel jPButtonNao;
    private javax.swing.JPanel jPButtonSim;
    private javax.swing.JPanel jPTopo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator;
    // End of variables declaration//GEN-END:variables

    public boolean isConfirm() {
        return confirm;
    }

    public static boolean confirm(Frame parent, String title, String mensagem) {
        ConfirmDialog confirmDialog = new ConfirmDialog(parent, title, mensagem);
        confirmDialog.setVisible(true);
        return confirmDialog.isConfirm();
    }
}
