/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.wendel.pdv.view;

import br.com.wendel.pdv.App;
import br.com.wendel.pdv.controller.PessoaCadastroController;
import br.com.wendel.pdv.entity.Cidade;
import br.com.wendel.pdv.util.Consulta;
import br.com.wendel.pdv.util.Cores;
import static br.com.wendel.pdv.util.Mensagem.enviarMensagemErro;
import br.com.wendel.pdv.util.TraversalPolicy;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import static java.util.Arrays.asList;
import javax.swing.BorderFactory;
import javax.swing.SwingUtilities;

/**
 *
 * @author INLOC01
 */
public class PessoaCadastroView extends javax.swing.JPanel implements ConsultaView {

    private PessoaCadastroController controller;
    private Cidade cidade;

    /**
     * Creates new form CaixaCadastroViewPanel
     *
     * @param id
     */
    public PessoaCadastroView(Long id) {
        this.controller = new PessoaCadastroController(id);
        initComponents();
//        if (this.controller.getCaixa() != null) {
//            this.jTFDescricao.setText(this.controller.getCaixa().getDescricao());
//        }
//        SwingUtilities.invokeLater(() -> {
//            this.jFTFCpfCnpj.requestFocusInWindow();
//        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTipo = new javax.swing.ButtonGroup();
        jPTopo = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        jLDescricao = new javax.swing.JLabel();
        jTFDescricao = new javax.swing.JTextField();
        jPButtonSalvar = new javax.swing.JPanel();
        jLButtonSalvar = new javax.swing.JLabel();
        jLIconButtonSalvar = new javax.swing.JLabel();
        jPButtonCancelar = new javax.swing.JPanel();
        jLButtonCancelar = new javax.swing.JLabel();
        jLIconButtonCancelar = new javax.swing.JLabel();
        jLDescricaoObrigatoria = new javax.swing.JLabel();
        jLTipo = new javax.swing.JLabel();
        jLTipoObrigatorio = new javax.swing.JLabel();
        jRBFisica = new javax.swing.JRadioButton();
        jRBJuridica = new javax.swing.JRadioButton();
        jFTFCpfCnpj = new javax.swing.JFormattedTextField();
        jLCpfCnpj = new javax.swing.JLabel();
        jLDataNascimento = new javax.swing.JLabel();
        jFTFDataNascimento = new javax.swing.JFormattedTextField();
        jLTelefoneCelular = new javax.swing.JLabel();
        jFTFTelefoneCelular = new javax.swing.JFormattedTextField();
        jLTelefoneCelular1 = new javax.swing.JLabel();
        jFTFTelefoneFixo = new javax.swing.JFormattedTextField();
        jCBCliente = new javax.swing.JCheckBox();
        jCBFornecedor = new javax.swing.JCheckBox();
        jLTelefoneCelular2 = new javax.swing.JLabel();
        jLLogradouro = new javax.swing.JLabel();
        jTFLogradouro = new javax.swing.JTextField();
        jLNumero = new javax.swing.JLabel();
        jTFNumero = new javax.swing.JTextField();
        jLComplemento = new javax.swing.JLabel();
        jTFComplemento = new javax.swing.JTextField();
        jLSetor = new javax.swing.JLabel();
        jTFSetor = new javax.swing.JTextField();
        jLCidade = new javax.swing.JLabel();
        jTFCodigoCidade = new javax.swing.JTextField();
        jTFDescricaoCidade = new javax.swing.JTextField();
        jLButtonProcurarCidade = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setFocusTraversalPolicy(new TraversalPolicy(asList(this.jRBFisica, this.jRBJuridica, this.jFTFCpfCnpj, this.jFTFDataNascimento, this.jTFDescricao, this.jFTFTelefoneCelular, this.jFTFTelefoneFixo, this.jCBCliente, this.jCBFornecedor, this.jTFLogradouro, this.jTFNumero, this.jTFComplemento, this.jTFSetor, this.jTFCodigoCidade, this.jTFDescricaoCidade, this.jLButtonProcurarCidade, this.jPButtonSalvar, this.jPButtonCancelar)));
        setFocusTraversalPolicyProvider(true);

        jPTopo.setBackground(new java.awt.Color(79, 195, 247));
        jPTopo.setPreferredSize(new java.awt.Dimension(85, 35));

        jLTitulo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLTitulo.setText("Cadastro de Pessoa");

        javax.swing.GroupLayout jPTopoLayout = new javax.swing.GroupLayout(jPTopo);
        jPTopo.setLayout(jPTopoLayout);
        jPTopoLayout.setHorizontalGroup(
            jPTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTopoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTitulo)
                .addContainerGap(569, Short.MAX_VALUE))
        );
        jPTopoLayout.setVerticalGroup(
            jPTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jLDescricao.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLDescricao.setText("Descrição");

        jTFDescricao.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTFDescricao.setToolTipText("Descrição do caixa");
        jTFDescricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFDescricaoFocusGained(evt);
            }
        });
        jTFDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFDescricaoKeyPressed(evt);
            }
        });

        jPButtonSalvar.setBackground(new java.awt.Color(0, 123, 255));
        jPButtonSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPButtonSalvar.setPreferredSize(new java.awt.Dimension(106, 35));
        jPButtonSalvar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPButtonSalvarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPButtonSalvarFocusLost(evt);
            }
        });
        jPButtonSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPButtonSalvarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPButtonSalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPButtonSalvarMouseExited(evt);
            }
        });
        jPButtonSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPButtonSalvarKeyPressed(evt);
            }
        });

        jLButtonSalvar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLButtonSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jLButtonSalvar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLButtonSalvar.setText("Salvar");

        jLIconButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wendel/pdv/images/icon_save.png"))); // NOI18N

        javax.swing.GroupLayout jPButtonSalvarLayout = new javax.swing.GroupLayout(jPButtonSalvar);
        jPButtonSalvar.setLayout(jPButtonSalvarLayout);
        jPButtonSalvarLayout.setHorizontalGroup(
            jPButtonSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPButtonSalvarLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLIconButtonSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPButtonSalvarLayout.setVerticalGroup(
            jPButtonSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(jLIconButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPButtonCancelar.setBackground(new java.awt.Color(220, 53, 69));
        jPButtonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPButtonCancelar.setPreferredSize(new java.awt.Dimension(106, 35));
        jPButtonCancelar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPButtonCancelarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPButtonCancelarFocusLost(evt);
            }
        });
        jPButtonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPButtonCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPButtonCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPButtonCancelarMouseExited(evt);
            }
        });
        jPButtonCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPButtonCancelarKeyPressed(evt);
            }
        });

        jLButtonCancelar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jLButtonCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLButtonCancelar.setText("Cancelar");

        jLIconButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wendel/pdv/images/icon_cancel.png"))); // NOI18N

        javax.swing.GroupLayout jPButtonCancelarLayout = new javax.swing.GroupLayout(jPButtonCancelar);
        jPButtonCancelar.setLayout(jPButtonCancelarLayout);
        jPButtonCancelarLayout.setHorizontalGroup(
            jPButtonCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPButtonCancelarLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLIconButtonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPButtonCancelarLayout.setVerticalGroup(
            jPButtonCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(jLIconButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLDescricaoObrigatoria.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLDescricaoObrigatoria.setForeground(new java.awt.Color(255, 0, 0));
        jLDescricaoObrigatoria.setText("*");

        jLTipo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLTipo.setText("Tipo");

        jLTipoObrigatorio.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLTipoObrigatorio.setForeground(new java.awt.Color(255, 0, 0));
        jLTipoObrigatorio.setText("*");

        jRBFisica.setBackground(new java.awt.Color(255, 255, 255));
        bgTipo.add(jRBFisica);
        jRBFisica.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jRBFisica.setSelected(true);
        jRBFisica.setText("Física");
        jRBFisica.setToolTipText("Pessoa Física");
        jRBFisica.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRBFisicaItemStateChanged(evt);
            }
        });
        jRBFisica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRBFisicaKeyPressed(evt);
            }
        });

        jRBJuridica.setBackground(new java.awt.Color(255, 255, 255));
        bgTipo.add(jRBJuridica);
        jRBJuridica.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jRBJuridica.setText("Jurídica");
        jRBJuridica.setToolTipText("Pessoa Jurídica");
        jRBJuridica.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRBJuridicaItemStateChanged(evt);
            }
        });
        jRBJuridica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRBJuridicaKeyPressed(evt);
            }
        });

        try {
            jFTFCpfCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFCpfCnpj.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jFTFCpfCnpj.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jFTFCpfCnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFTFCpfCnpjFocusGained(evt);
            }
        });
        jFTFCpfCnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFTFCpfCnpjKeyPressed(evt);
            }
        });

        jLCpfCnpj.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLCpfCnpj.setText("CPF");

        jLDataNascimento.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLDataNascimento.setText("Data de Nascimento");

        try {
            jFTFDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFDataNascimento.setToolTipText("Data de nascimento da pessoa");
        jFTFDataNascimento.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jFTFDataNascimento.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jFTFDataNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFTFDataNascimentoFocusGained(evt);
            }
        });
        jFTFDataNascimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFTFDataNascimentoKeyPressed(evt);
            }
        });

        jLTelefoneCelular.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLTelefoneCelular.setText("Telefone Celular");

        try {
            jFTFTelefoneCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFTelefoneCelular.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jFTFTelefoneCelular.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jFTFTelefoneCelular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFTFTelefoneCelularFocusGained(evt);
            }
        });
        jFTFTelefoneCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFTFTelefoneCelularKeyPressed(evt);
            }
        });

        jLTelefoneCelular1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLTelefoneCelular1.setText("Telefone Fixo");

        try {
            jFTFTelefoneFixo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFTelefoneFixo.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jFTFTelefoneFixo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jFTFTelefoneFixo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFTFTelefoneFixoFocusGained(evt);
            }
        });
        jFTFTelefoneFixo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFTFTelefoneFixoKeyPressed(evt);
            }
        });

        jCBCliente.setBackground(new java.awt.Color(255, 255, 255));
        jCBCliente.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jCBCliente.setText("Cliente");
        jCBCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCBClienteKeyPressed(evt);
            }
        });

        jCBFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        jCBFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jCBFornecedor.setText("Fornecedor");
        jCBFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCBFornecedorKeyPressed(evt);
            }
        });

        jLTelefoneCelular2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLTelefoneCelular2.setText("A pessoa é?");

        jLLogradouro.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLLogradouro.setText("Logradouro");

        jTFLogradouro.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTFLogradouro.setToolTipText("Descrição do caixa");
        jTFLogradouro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFLogradouroFocusGained(evt);
            }
        });
        jTFLogradouro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFLogradouroKeyPressed(evt);
            }
        });

        jLNumero.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLNumero.setText("Número");

        jTFNumero.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTFNumero.setToolTipText("Descrição do caixa");
        jTFNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFNumeroFocusGained(evt);
            }
        });
        jTFNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFNumeroKeyPressed(evt);
            }
        });

        jLComplemento.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLComplemento.setText("Complemento");

        jTFComplemento.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTFComplemento.setToolTipText("Descrição do caixa");
        jTFComplemento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFComplementoFocusGained(evt);
            }
        });
        jTFComplemento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFComplementoKeyPressed(evt);
            }
        });

        jLSetor.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLSetor.setText("Setor");

        jTFSetor.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTFSetor.setToolTipText("Descrição do caixa");
        jTFSetor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFSetorFocusGained(evt);
            }
        });
        jTFSetor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFSetorKeyPressed(evt);
            }
        });

        jLCidade.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLCidade.setText("Cidade");

        jTFCodigoCidade.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTFCodigoCidade.setToolTipText("Descrição do caixa");
        jTFCodigoCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFCodigoCidadeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFCodigoCidadeFocusLost(evt);
            }
        });
        jTFCodigoCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFCodigoCidadeKeyPressed(evt);
            }
        });

        jTFDescricaoCidade.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTFDescricaoCidade.setToolTipText("Descrição do caixa");
        jTFDescricaoCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFDescricaoCidadeFocusGained(evt);
            }
        });
        jTFDescricaoCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFDescricaoCidadeKeyPressed(evt);
            }
        });

        jLButtonProcurarCidade.setBackground(new java.awt.Color(102, 228, 112));
        jLButtonProcurarCidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLButtonProcurarCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wendel/pdv/images/icon_search.png"))); // NOI18N
        jLButtonProcurarCidade.setToolTipText("");
        jLButtonProcurarCidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLButtonProcurarCidade.setOpaque(true);
        jLButtonProcurarCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLButtonProcurarCidadeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jLButtonProcurarCidadeFocusLost(evt);
            }
        });
        jLButtonProcurarCidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLButtonProcurarCidadeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLButtonProcurarCidadeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLButtonProcurarCidadeMouseExited(evt);
            }
        });
        jLButtonProcurarCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLButtonProcurarCidadeKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTopo, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFDescricao)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTFLogradouro, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNumero)
                            .addComponent(jTFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLComplemento)
                            .addComponent(jTFComplemento)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLDescricao)
                                .addGap(0, 0, 0)
                                .addComponent(jLDescricaoObrigatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLTipo)
                                        .addGap(0, 0, 0)
                                        .addComponent(jLTipoObrigatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jRBFisica)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRBJuridica)))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFTFCpfCnpj, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                    .addComponent(jLCpfCnpj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jFTFDataNascimento)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFTFTelefoneCelular)
                                    .addComponent(jLTelefoneCelular, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFTFTelefoneFixo, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(jLTelefoneCelular1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCBCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCBFornecedor))
                                    .addComponent(jLTelefoneCelular2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLLogradouro)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLSetor)
                                    .addComponent(jTFSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLCidade)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTFCodigoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTFDescricaoCidade)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLButtonProcurarCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPTopo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLTipo)
                                    .addComponent(jLTipoObrigatorio)
                                    .addComponent(jLCpfCnpj)
                                    .addComponent(jLDataNascimento))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jFTFCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFTFDataNascimento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLDescricao)
                                    .addComponent(jLDescricaoObrigatoria))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRBJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRBFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLTelefoneCelular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFTFTelefoneCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCBCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCBFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLTelefoneCelular1)
                            .addComponent(jLTelefoneCelular2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFTFTelefoneFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLLogradouro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTFLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLComplemento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSetor)
                    .addComponent(jLCidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLButtonProcurarCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFDescricaoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFCodigoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPButtonSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonSalvarMouseEntered
        SwingUtilities.invokeLater(() -> {
            this.jPButtonSalvar.setBackground(Cores.COR_BOTAO_SALVAR_ENTERED);
        });
    }//GEN-LAST:event_jPButtonSalvarMouseEntered

    private void jPButtonSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonSalvarMouseExited
        SwingUtilities.invokeLater(() -> {
            this.jPButtonSalvar.setBackground(Cores.COR_BOTAO_SALVAR);
        });
    }//GEN-LAST:event_jPButtonSalvarMouseExited

    private void jPButtonCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonCancelarMouseEntered
        SwingUtilities.invokeLater(() -> {
            this.jPButtonCancelar.setBackground(Cores.COR_BOTAO_CANCELAR_ENTERED);
        });
    }//GEN-LAST:event_jPButtonCancelarMouseEntered

    private void jPButtonCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonCancelarMouseExited
        SwingUtilities.invokeLater(() -> {
            this.jPButtonCancelar.setBackground(Cores.COR_BOTAO_CANCELAR);
        });
    }//GEN-LAST:event_jPButtonCancelarMouseExited

    private void jPButtonSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonSalvarMouseClicked
        this.acaoSalvar();
    }//GEN-LAST:event_jPButtonSalvarMouseClicked

    private void jPButtonCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonCancelarMouseClicked
        try {
            App.getInstance().getPrincipalView().mostraTelaCaixas();
        } catch (Exception e) {
            enviarMensagemErro(e.getMessage());
        }
    }//GEN-LAST:event_jPButtonCancelarMouseClicked

    private void acaoSalvar() {
        try {
//            if (this.controller.salvarCaixa(this.jTFCodigo.getText(), this.jTFDescricao.getText())) {
//                App.getInstance().getPrincipalView().mostraTelaCaixas();
//            }
        } catch (Exception e) {
            enviarMensagemErro(e.getMessage());
        }
    }

    private void jTFDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDescricaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            SwingUtilities.invokeLater(() -> {
                this.jFTFTelefoneCelular.requestFocusInWindow();
            });
        }
    }//GEN-LAST:event_jTFDescricaoKeyPressed

    private void jPButtonSalvarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPButtonSalvarFocusGained
        SwingUtilities.invokeLater(() -> {
            this.jPButtonSalvar.setBorder(BorderFactory.createDashedBorder(null, 1, 5, 5, false));
        });
    }//GEN-LAST:event_jPButtonSalvarFocusGained

    private void jPButtonSalvarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPButtonSalvarFocusLost
        SwingUtilities.invokeLater(() -> {
            this.jPButtonSalvar.setBorder(null);
        });
    }//GEN-LAST:event_jPButtonSalvarFocusLost

    private void jPButtonCancelarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPButtonCancelarFocusGained
        SwingUtilities.invokeLater(() -> {
            this.jPButtonCancelar.setBorder(BorderFactory.createDashedBorder(null, 1, 5, 5, false));
        });
    }//GEN-LAST:event_jPButtonCancelarFocusGained

    private void jPButtonCancelarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPButtonCancelarFocusLost
        SwingUtilities.invokeLater(() -> {
            this.jPButtonCancelar.setBorder(null);
        });
    }//GEN-LAST:event_jPButtonCancelarFocusLost

    private void jPButtonSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPButtonSalvarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_SPACE) {
            this.acaoSalvar();
        }
    }//GEN-LAST:event_jPButtonSalvarKeyPressed

    private void jPButtonCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPButtonCancelarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_SPACE) {
            this.jPButtonCancelarMouseClicked(null);
        }
    }//GEN-LAST:event_jPButtonCancelarKeyPressed

    private void jTFDescricaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFDescricaoFocusGained
        SwingUtilities.invokeLater(() -> {
            this.jTFDescricao.selectAll();
        });
    }//GEN-LAST:event_jTFDescricaoFocusGained

    private void jRBFisicaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRBFisicaItemStateChanged
        try {
            if (this.jRBFisica.isSelected()) {
                this.jLCpfCnpj.setText("CPF");
                this.jFTFCpfCnpj.setToolTipText("CPF da pessoa física");
                this.jFTFCpfCnpj.setValue("");
                this.jFTFCpfCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
                this.jLDataNascimento.setVisible(true);
                this.jFTFDataNascimento.setVisible(true);
            }
        } catch (ParseException e) {
            enviarMensagemErro(e.getMessage());
        }
    }//GEN-LAST:event_jRBFisicaItemStateChanged

    private void jRBJuridicaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRBJuridicaItemStateChanged
        try {
            if (this.jRBJuridica.isSelected()) {
                this.jLCpfCnpj.setText("CPNJ");
                this.jFTFCpfCnpj.setToolTipText("CNPJ da pessoa jurídica");
                this.jFTFCpfCnpj.setValue("");
                this.jFTFCpfCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
                this.jLDataNascimento.setVisible(false);
                this.jFTFDataNascimento.setVisible(false);
            }
        } catch (ParseException e) {
            enviarMensagemErro(e.getMessage());
        }
    }//GEN-LAST:event_jRBJuridicaItemStateChanged

    private void jRBFisicaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRBFisicaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            SwingUtilities.invokeLater(() -> {
                this.jRBJuridica.requestFocusInWindow();
            });
        }
    }//GEN-LAST:event_jRBFisicaKeyPressed

    private void jRBJuridicaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRBJuridicaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            SwingUtilities.invokeLater(() -> {
                this.jFTFCpfCnpj.requestFocusInWindow();
            });
        }
    }//GEN-LAST:event_jRBJuridicaKeyPressed

    private void jFTFCpfCnpjKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTFCpfCnpjKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            SwingUtilities.invokeLater(() -> {
                if (this.jRBFisica.isSelected()) {
                    this.jFTFDataNascimento.requestFocusInWindow();
                } else {
                    this.jTFDescricao.requestFocusInWindow();
                }
            });
        }
    }//GEN-LAST:event_jFTFCpfCnpjKeyPressed

    private void jFTFDataNascimentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTFDataNascimentoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            SwingUtilities.invokeLater(() -> {
                this.jTFDescricao.requestFocusInWindow();
            });
        }
    }//GEN-LAST:event_jFTFDataNascimentoKeyPressed

    private void jFTFTelefoneCelularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTFTelefoneCelularKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            SwingUtilities.invokeLater(() -> {
                this.jFTFTelefoneFixo.requestFocusInWindow();
            });
        }
    }//GEN-LAST:event_jFTFTelefoneCelularKeyPressed

    private void jFTFTelefoneFixoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTFTelefoneFixoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            SwingUtilities.invokeLater(() -> {
                this.jCBCliente.requestFocusInWindow();
            });
        }
    }//GEN-LAST:event_jFTFTelefoneFixoKeyPressed

    private void jTFLogradouroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFLogradouroFocusGained
        SwingUtilities.invokeLater(() -> {
            this.jTFLogradouro.selectAll();
        });
    }//GEN-LAST:event_jTFLogradouroFocusGained

    private void jTFLogradouroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFLogradouroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            SwingUtilities.invokeLater(() -> {
                this.jTFNumero.requestFocusInWindow();
            });
        }
    }//GEN-LAST:event_jTFLogradouroKeyPressed

    private void jTFNumeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFNumeroFocusGained
        SwingUtilities.invokeLater(() -> {
            this.jTFNumero.selectAll();
        });
    }//GEN-LAST:event_jTFNumeroFocusGained

    private void jTFNumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNumeroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            SwingUtilities.invokeLater(() -> {
                this.jTFComplemento.requestFocusInWindow();
            });
        }
    }//GEN-LAST:event_jTFNumeroKeyPressed

    private void jTFComplementoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFComplementoFocusGained
        SwingUtilities.invokeLater(() -> {
            this.jTFComplemento.selectAll();
        });
    }//GEN-LAST:event_jTFComplementoFocusGained

    private void jTFComplementoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFComplementoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            SwingUtilities.invokeLater(() -> {
                this.jTFSetor.requestFocusInWindow();
            });
        }
    }//GEN-LAST:event_jTFComplementoKeyPressed

    private void jTFSetorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFSetorFocusGained
        SwingUtilities.invokeLater(() -> {
            this.jTFSetor.selectAll();
        });
    }//GEN-LAST:event_jTFSetorFocusGained

    private void jTFSetorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFSetorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            SwingUtilities.invokeLater(() -> {
                this.jTFCodigoCidade.requestFocusInWindow();
            });
        }
    }//GEN-LAST:event_jTFSetorKeyPressed

    private void jTFCodigoCidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFCodigoCidadeFocusGained
        SwingUtilities.invokeLater(() -> {
            this.jTFCodigoCidade.selectAll();
        });
    }//GEN-LAST:event_jTFCodigoCidadeFocusGained

    private void jTFCodigoCidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCodigoCidadeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            SwingUtilities.invokeLater(() -> {
                this.jPButtonSalvar.requestFocusInWindow();
            });
        }
    }//GEN-LAST:event_jTFCodigoCidadeKeyPressed

    private void jTFDescricaoCidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFDescricaoCidadeFocusGained
        SwingUtilities.invokeLater(() -> {
            this.jTFDescricaoCidade.selectAll();
        });
    }//GEN-LAST:event_jTFDescricaoCidadeFocusGained

    private void jTFDescricaoCidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDescricaoCidadeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDescricaoCidadeKeyPressed

    private void jLButtonProcurarCidadeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLButtonProcurarCidadeMouseEntered
        SwingUtilities.invokeLater(() -> {
            this.jLButtonProcurarCidade.setBackground(Cores.COR_BOTAO_PROCURAR_ENTERED);
        });
    }//GEN-LAST:event_jLButtonProcurarCidadeMouseEntered

    private void jLButtonProcurarCidadeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLButtonProcurarCidadeMouseExited
        SwingUtilities.invokeLater(() -> {
            this.jLButtonProcurarCidade.setBackground(Cores.COR_BOTAO_PROCURAR);
        });
    }//GEN-LAST:event_jLButtonProcurarCidadeMouseExited

    private void jLButtonProcurarCidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLButtonProcurarCidadeFocusGained
        SwingUtilities.invokeLater(() -> {
            this.jLButtonProcurarCidade.setBorder(BorderFactory.createDashedBorder(null, 1, 5, 5, false));
        });
    }//GEN-LAST:event_jLButtonProcurarCidadeFocusGained

    private void jLButtonProcurarCidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLButtonProcurarCidadeFocusLost
        SwingUtilities.invokeLater(() -> {
            this.jLButtonProcurarCidade.setBorder(null);
        });
    }//GEN-LAST:event_jLButtonProcurarCidadeFocusLost

    private void jLButtonProcurarCidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLButtonProcurarCidadeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_SPACE) {
            try {
                this.acaoAbrirConsultaCidade();
            } catch (Exception e) {
                enviarMensagemErro(e.getMessage());
            }
        }
    }//GEN-LAST:event_jLButtonProcurarCidadeKeyPressed

    private void jLButtonProcurarCidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLButtonProcurarCidadeMouseClicked
        try {
            this.acaoAbrirConsultaCidade();
        } catch (Exception e) {
            enviarMensagemErro(e.getMessage());
        }
    }//GEN-LAST:event_jLButtonProcurarCidadeMouseClicked

    private void jCBClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCBClienteKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            SwingUtilities.invokeLater(() -> {
                this.jCBFornecedor.requestFocusInWindow();
            });
        }
    }//GEN-LAST:event_jCBClienteKeyPressed

    private void jCBFornecedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCBFornecedorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            SwingUtilities.invokeLater(() -> {
                this.jTFLogradouro.requestFocusInWindow();
            });
        }
    }//GEN-LAST:event_jCBFornecedorKeyPressed

    private void jFTFCpfCnpjFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTFCpfCnpjFocusGained
        SwingUtilities.invokeLater(() -> {
            this.jFTFCpfCnpj.selectAll();
        });
    }//GEN-LAST:event_jFTFCpfCnpjFocusGained

    private void jFTFDataNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTFDataNascimentoFocusGained
        SwingUtilities.invokeLater(() -> {
            this.jFTFDataNascimento.selectAll();
        });
    }//GEN-LAST:event_jFTFDataNascimentoFocusGained

    private void jFTFTelefoneCelularFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTFTelefoneCelularFocusGained
        SwingUtilities.invokeLater(() -> {
            this.jFTFTelefoneCelular.selectAll();
        });
    }//GEN-LAST:event_jFTFTelefoneCelularFocusGained

    private void jFTFTelefoneFixoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTFTelefoneFixoFocusGained
        SwingUtilities.invokeLater(() -> {
            this.jFTFTelefoneFixo.selectAll();
        });
    }//GEN-LAST:event_jFTFTelefoneFixoFocusGained

    private void jTFCodigoCidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFCodigoCidadeFocusLost
        try {
            String codigoNovo = this.jTFCodigoCidade.getText();
            if (codigoNovo != null && !codigoNovo.isEmpty()) {
                if (this.cidade == null
                        || !this.cidade.getId().equals(Long.valueOf(codigoNovo))) {
                    Cidade cidadeNova = this.controller.obterCidade(Long.valueOf(codigoNovo));
                    if (cidadeNova != null && cidadeNova.getId() != null) {
                        this.preencheCidade(cidadeNova);
                    } else {
                        this.limparCidade();
                        enviarMensagemErro("Cidade inexistente!");
                        this.jTFCodigoCidade.requestFocusInWindow();
                    }
                }
            } else {
                this.limparCidade();
            }
        } catch (Exception e) {
            enviarMensagemErro(e.getMessage());
        }
    }//GEN-LAST:event_jTFCodigoCidadeFocusLost

    private void limparCidade() {
        this.cidade = null;
        this.jTFCodigoCidade.setText("");
        this.jTFDescricaoCidade.setText("");
    }

    private void preencheCidade(Cidade cidade) {
        this.cidade = cidade;
        this.jTFCodigoCidade.setText(cidade.getId().toString());
        this.jTFDescricaoCidade.setText(cidade.getDescricao());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTipo;
    private javax.swing.JCheckBox jCBCliente;
    private javax.swing.JCheckBox jCBFornecedor;
    private javax.swing.JFormattedTextField jFTFCpfCnpj;
    private javax.swing.JFormattedTextField jFTFDataNascimento;
    private javax.swing.JFormattedTextField jFTFTelefoneCelular;
    private javax.swing.JFormattedTextField jFTFTelefoneFixo;
    private javax.swing.JLabel jLButtonCancelar;
    private javax.swing.JLabel jLButtonProcurarCidade;
    private javax.swing.JLabel jLButtonSalvar;
    private javax.swing.JLabel jLCidade;
    private javax.swing.JLabel jLComplemento;
    private javax.swing.JLabel jLCpfCnpj;
    private javax.swing.JLabel jLDataNascimento;
    private javax.swing.JLabel jLDescricao;
    private javax.swing.JLabel jLDescricaoObrigatoria;
    private javax.swing.JLabel jLIconButtonCancelar;
    private javax.swing.JLabel jLIconButtonSalvar;
    private javax.swing.JLabel jLLogradouro;
    private javax.swing.JLabel jLNumero;
    private javax.swing.JLabel jLSetor;
    private javax.swing.JLabel jLTelefoneCelular;
    private javax.swing.JLabel jLTelefoneCelular1;
    private javax.swing.JLabel jLTelefoneCelular2;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JLabel jLTipoObrigatorio;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JPanel jPButtonCancelar;
    private javax.swing.JPanel jPButtonSalvar;
    private javax.swing.JPanel jPTopo;
    private javax.swing.JRadioButton jRBFisica;
    private javax.swing.JRadioButton jRBJuridica;
    private javax.swing.JTextField jTFCodigoCidade;
    private javax.swing.JTextField jTFComplemento;
    private javax.swing.JTextField jTFDescricao;
    private javax.swing.JTextField jTFDescricaoCidade;
    private javax.swing.JTextField jTFLogradouro;
    private javax.swing.JTextField jTFNumero;
    private javax.swing.JTextField jTFSetor;
    // End of variables declaration//GEN-END:variables

    private void acaoAbrirConsultaCidade() throws Exception {
        Consulta.getInstance().adicionarJanela(this, "idCidade");
        PrincipalView principalView = App.getInstance().getPrincipalView();
        CidadesView cidadesView = principalView.getTelaCidades();
        cidadesView.carregaTela();
        principalView.mostraConteudo(cidadesView);
    }

    @Override
    public void acaoSelecionarConsulta(String key, Object value) throws Exception {
        if (key.equals("idCidade")) {
            this.preencheCidade(this.controller.obterCidade((Long) value));
            this.jTFCodigoCidade.requestFocusInWindow();
        }
    }
}
